stages:
    - test

.test: &go_test_template
    stage: test
    script:
        - go mod download
        - go test -race -tags=livetest ./...

linter:
    stage: test
    image: golangci/golangci-lint:v1.28
    script:
        - go mod download
        - golangci-lint run ./...

coverage:
    stage: test
    image: golang:1.14
    services: []
    before_script:
        - ""
    script:
        - go mod download
        - ./script/coverage.sh

go-1.13:
    <<: *go_test_template
    image: golang:1.13

go-1.14:
    <<: *go_test_template
    image: golang:1.14

go-rc:
    <<: *go_test_template
    stage: test
    image: golang:rc
    allow_failure: true

.gopherjs_test: &gopherjs_test_template
  <<: *go_test_template
  before_script:
    - curl -sL https://deb.nodesource.com/setup_12.x | bash -
    - apt-get update -qq && apt-get install -y nodejs
  script:
    - npm install -g npm@7.5.2 && npm update
    - npm install
    - npm install source-map-support
    - mkdir -p /tmp/src
    - ( cd /tmp && go install github.com/gopherjs/gopherjs@${GOPHERJS_TAG} )
    - npm install -S https://github.com/gopherjs/gopherjs#${GOPHERJS_TAG} && node -r syscall
    - gopherjs test ./...

gopherjs-1.16:
  <<: *gopherjs_test_template
  image: golang:1.16
  variables:
    GOPHERJS_TAG: 1.16.4+go1.16.7
