dist: trusty
sudo: required
services:
    - docker
cache:
    directories:
        - node_modules
        - $HOME/gopath/pkg

language: go

os:
    - linux

go:
    - 1.9.x
    - 1.10.x
    - 1.11.x
    - master
env:
    matrix:
        - MODE=standard

matrix:
    fast_finish: true
    allow_failures:
        - go: master
    include:
        - go: 1.11.x
          env: MODE=gopherjs
        - go: 1.11.x
          env: MODE=linter
        - go: 1.11.x
          env: MODE=coverage

install:
    - ./travis/install.sh $MODE

script:
    - ./travis/test.sh $MODE
